[package]
authors = ["David Peter <mail@david-peter.de>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "fd is a simple, fast and user-friendly alternative to find."
exclude = ["/benchmarks/*"]
homepage = "https://github.com/sharkdp/fd"
keywords = [
    "search",
    "find",
    "file",
    "filesystem",
    "tool",
]
license = "MIT/Apache-2.0"
name = "fd-find"
readme = "README.md"
repository = "https://github.com/sharkdp/fd"
version = "8.1.1"
edition= "2018"

[badges.appveyor]
repository = "sharkdp/fd"

[badges.travis-ci]
repository = "sharkdp/fd"

[[bin]]
name = "fd"
path = "src/main.rs"

[build-dependencies]
clap = "2.33.1"
version_check = "0.9.2"

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
ignore = "0.4.16"
lazy_static = "1.4.0"
num_cpus = "1.13.0"
regex = "1.3.9"
regex-syntax = "0.6.18"
ctrlc = "3.1.4"
humantime = "2.0.1"
lscolors = "0.7.1"
globset = "0.4.5"
anyhow = "1.0.31"
dirs = "3.0.0"

[dependencies.clap]
version = "2.33.1"
features = ["suggestions", "color", "wrap_help"]

[target.'cfg(unix)'.dependencies]
users = "0.10.0"

[target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
libc = "0.2.71"

# FIXME: Re-enable jemalloc on macOS
# jemalloc is currently disabled on macOS due to a bug in jemalloc in combination with macOS
# Catalina. See https://github.com/sharkdp/fd/issues/498 for details.
[target.'cfg(all(not(windows), not(target_os = "macos"), not(target_env = "musl")))'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
diff = "0.1.12"
tempdir = "0.3.7"
filetime = "0.2.10"

[profile.release]
lto = true
codegen-units = 1

[features]
fd-no-gitversion = []
